name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
    - name: PHP Mess Detector
      uses: php-actions/phpmd@v1
      with:
        php_version: 8.1
        path: lib/
        output: text
        ruleset: tst/xmltests/ruleset.xml
        args: --ignore-violations-on-exit
    - uses: php-actions/phpunit@v3
      env:
          XDEBUG_MODE: coverage
      with:
          memory_limit: 512M
          php_extensions: "gd mbstring xdebug" 
          configuration: "phpunit.xml"
          coverage_cobertura: "coverage.xml"
          version: 9.6.11
    - name: Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: "coverage.xml"
        format: markdown
        output: both
    - name: PHP Code Sniffer
      uses: php-actions/phpcs@v1
      with:
        php_version: 8.1
        standard: psr1
        path: lib/
    - uses: php-actions/phpstan@v3
      with:
        path: lib/
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST_AWS }}
        username: ${{ secrets.USERNAME_AWS }}
        port: ${{ secrets.PORT_AWS }}
        key: ${{ secrets.SSH_AWS }}
        source: "*"
        target: /var/www/PrivateBin
    - name: Add markdown comment
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
            
    # ... then your own project steps ...
