name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
    - uses: php-actions/phpunit@v3
      env:
          XDEBUG_MODE: coverage
      with:
          memory_limit: 256M
          php_extensions: "gd mbstring xdebug" 
          configuration: "phpunit.xml"
          coverage_cobertura: "coverage.xml"
          version: 9.6.11
    - name: Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: "coverage.xml"
            
    # ... then your own project steps ...
